databases:
  - name: canlee_database
    databaseName: canlee_db
    user: notaigbe

services:
  - type: web
    name: hms
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn HMS.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: canlee_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4