# Generated by Django 4.1.4 on 2022-12-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_alter_room_roomtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='availability',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('occupied', 'Occupied'), ('vacant', 'Vacant')], default='vacant', max_length=10),
        ),
    ]
