# Generated by Django 4.1.4 on 2022-12-28 04:29

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_remove_room_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='statusDuration',
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(null=True),
        ),
    ]
