# Generated by Django 4.1.4 on 2022-12-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_room_statusduration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='statusEndDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='statusStartDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
