# Generated by Django 4.1.4 on 2022-12-29 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_alter_room_statusenddate_alter_room_statusstartdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='statusDuration',
        ),
    ]
